<a href="https://colab.research.google.com/github/brianb1/2017Challenges/blob/master/Copy_of_Python_For_DataScience_Notes.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

***<center> Notes for Python for Data Science  (Intro to NumPy and Pandas)</center> ***

In [ ]:
#Importing Packages
import numpy as np
import pandas as pd

**NumPy Arrays are like Lists but allow for Arthmetic Operations to be performed easily and faster**

In [ ]:
#Suppose we have the 2 lists below representing revenue and cost data for 8 quarters below.
#The first 4 elements represent the 1st year's quarterly data.
#The last 4 elements represent the 2nd year's quarterly data. 
rev_list = [300,350,450,550,320,340,440,580]
cost_list = [250,280,320,360,280,270,340,400]

#Suppose we want to calculate the profit and the following line of code:
#Profit = rev - cost 
#This will throw an error. NumPy arrays on the otherhand allow us to perform arthimetic operations.

#How to create a numpy array => np.array(Insert a list here)
#Note that unlike a list, all numpy array elements have to be of the same datatype. 

#For example:

rev_array = np.array(rev_list)
cost_array = np.array(cost_list)

#Now we can calculate the profit more easily:
profit_array = rev_array - cost_array 
print(profit_array)

#You can perform standard arithmetic operations on numpy arrays such as +,-,*,/ etc.

#You can filter arrays as well. 
#This prints out only the values where the element is greater than 300. 

print(rev_array[rev_array>300])

[ 50  70 130 190  40  70 100 180]
[350 450 550 320 340 440 580]

**<center>Shaping Data Using NumPy</center>**

In [ ]:
#You can view the shape of your array be assessing the .shape property. 
print(rev_array.shape) #Note (8,) indicates 8 rows and 0 columns

#You need to use the reshape method on your array if we you want to structure it. 

print(rev_array.reshape(2,4)) #This results in a 2-d array with 2 rows and 4 columns

#Note that when you use the reshape method, the underlying array is left unchanged.
#One way you can still assess the product of the reshape method is to assign it to a variable.

rev_array_reshaped = rev_array.reshape(2,4,1) #We are reshaping the array to be 3-d here.
print(rev_array_reshaped)

(8,)
[[300 350 450 550]
 [320 340 440 580]]
[[[300]
  [350]
  [450]
  [550]]

 [[320]
  [340]
  [440]
  [580]]]

**<center> Slicing Your Data -AKA Getting What You Want from the Data </center>**

In [ ]:
#The syntax for slicing your data is similar to slicing data from lists. 
#Note that python indexing starts with 0. 

first_quarter_first_year = rev_array[0]

print(first_quarter_first_year)

#Suppose we want to get first three quarters' revenue 

print(rev_array[:3]) #0,1,2 elements gets outputted

300
[300 350 450]

**<center> Moving onto Pandas- How do you create a DataFrame? </center> **

In [ ]:
#In Pandas, we work with dataframes.

#One way of you can get data is to convert dictionary into a dataframe 

sample_dictionary = [{'a':1,'b':2,'c':3,'d':4},
                    {'a':100,'b':200,'c':300,'d':400}]

df_from_dictionary = pd.DataFrame(sample_dictionary)

print(df_from_dictionary)

     a    b    c    d
0    1    2    3    4
1  100  200  300  400

In [ ]:
#You can also import data from csv, html, xlsx (excel) formats to create a dataframe.

#Suppose you want to read from a csv file. You use Panda's read_csv method. 

df = pd.read_csv("https://raw.githubusercontent.com/gpalrepo/inclass_practice/master/Shark%20Tank%20Companies.csv")

**<center>Some Exploratory Data Analysis</center>**

In [ ]:
print(df.shape) #shape property indicates number of rows and columns in your dataframe.
print(df.info()) # Info method tells you the columns and associated datatypes.

(495, 19)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 495 entries, 0 to 494
Data columns (total 19 columns):
deal                      495 non-null bool
description               495 non-null object
episode                   495 non-null int64
category                  495 non-null object
entrepreneurs             423 non-null object
location                  495 non-null object
website                   457 non-null object
askedFor                  495 non-null int64
exchangeForStake          495 non-null int64
valuation                 495 non-null int64
season                    495 non-null int64
shark1                    495 non-null object
shark2                    495 non-null object
shark3                    495 non-null object
shark4                    495 non-null object
shark5                    495 non-null object
title                     495 non-null object
episode-season            495 non-null object
Multiple Entreprenuers    495 non-null bool
dtypes: bool(2), int64(5), object(12)
memory usage: 66.8+ KB
None

In [ ]:
print(df.head()) #This prints out the first 5 rows in a dataset
print(df.tail()) #This prints out the last 5 rows in a dataset

    deal                                        description  episode  \
0  False             Bluetooth device implant for your ear.        1
1   True  Retail and wholesale pie factory with two reta...        1
2   True  Ava the Elephant is a godsend for frazzled par...        1
3  False  Organizing, packing, and moving services deliv...        1
4  False  Interactive media centers for healthcare waiti...        1

              category                entrepreneurs      location  \
0            Novelties               Darrin Johnson  St. Paul, MN
1       Specialty Food                   Tod Wilson  Somerset, NJ
2  Baby and Child Care              Tiffany Krumins   Atlanta, GA
3    Consumer Services  Nick Friedman, Omar Soliman     Tampa, FL
4    Consumer Services               Kevin Flannery      Cary, NC

                               website  askedFor  exchangeForStake  valuation  \
0                                  NaN   1000000                15    6666667
1                  http://whybake.com/    460000                10    4600000
2       http://www.avatheelephant.com/     50000                15     333333
3  http://collegehunkshaulingjunk.com/    250000                25    1000000
4              http://www.wispots.com/   1200000                10   12000000

   season            shark1           shark2         shark3        shark4  \
0       1  Barbara Corcoran  Robert Herjavec  Kevin O'Leary  Daymond John
1       1  Barbara Corcoran  Robert Herjavec  Kevin O'Leary  Daymond John
2       1  Barbara Corcoran  Robert Herjavec  Kevin O'Leary  Daymond John
3       1  Barbara Corcoran  Robert Herjavec  Kevin O'Leary  Daymond John
4       1  Barbara Corcoran  Robert Herjavec  Kevin O'Leary  Daymond John

             shark5                        title episode-season  \
0  Kevin Harrington                    Ionic Ear            1-1
1  Kevin Harrington        Mr. Tod's Pie Factory            1-1
2  Kevin Harrington             Ava the Elephant            1-1
3  Kevin Harrington  College Foxes Packing Boxes            1-1
4  Kevin Harrington                      Wispots            1-1

   Multiple Entreprenuers
0                   False
1                   False
2                   False
3                   False
4                   False
      deal                                        description  episode  \
490   True  Zoom Interiors is a virtual service for interi...       28
491   True  Spikeball started out as a casual outdoors gam...       29
492   True  Shark Wheel is out to literally reinvent the w...       29
493  False  Adriana Montano wants to open the first Cat Ca...       29
494   True  Sway Motorsports makes a three-wheeled, all-el...       29

               category                                      entrepreneurs  \
490     Online Services  Beatrice Fischel-Bock, Madeine Fraser & Lizzie...
491      Toys and Games                                        Chris Ruder
492  Outdoor Recreation                   David Patrick and Zack Fleishman
493       Entertainment                                    Adriana Montano
494          Automotive                                         Joe Wilcox

             location                         website  askedFor  \
490  Philadelphia, PA       https://zoominteriors.com    100000
491       Chicago, IL            http://spikeball.com    500000
492   Lake Forest, CA       http://www.sharkwheel.com    100000
493    Boca Raton, FL      http://gatocafeflorida.com    100000
494     Palo Alto, CA  http://www.swaymotorsports.com    300000

     exchangeForStake  valuation  season        shark1            shark2  \
490                20     500000       6  Lori Greiner  Barbara Corcoran
491                10    5000000       6  Lori Greiner     Kevin O'Leary
492                 5    2000000       6  Lori Greiner     Kevin O'Leary
493                20     500000       6  Lori Greiner     Kevin O'Leary
494                10    3000000       6  Lori Greiner     Kevin O'Leary

              shark3         shark4        shark5             title  \
490  Robert Herjavec  Kevin O'Leary    Mark Cuban    Zoom Interiors
491     Daymond John     Mark Cuban  Nick Woodman         Spikeball
492     Daymond John     Mark Cuban  Nick Woodman       Shark Wheel
493     Daymond John     Mark Cuban  Nick Woodman         Gato Cafe
494     Daymond John     Mark Cuban  Nick Woodman  Sway Motorsports

    episode-season  Multiple Entreprenuers
490           6-28                   False
491           6-29                   False
492           6-29                    True
493           6-29                   False
494           6-29                   False

In [ ]:
print(df.columns) #This prints out just the names of the columns 

#You can rename a column's name using the rename method. 
#You need to make sure the key is the orignal name of the column 
#and the value is the new name. 

#Inplace=True ensures that you make the changes to the existing dataframe itself.

df.rename(columns={'website':'company_website'},inplace=True) 

#Let's check to see the column names have been changed.
print(df.columns)

Index(['deal', 'description', 'episode', 'category', 'entrepreneurs',
       'location', 'website', 'askedFor', 'exchangeForStake', 'valuation',
       'season', 'shark1', 'shark2', 'shark3', 'shark4', 'shark5', 'title',
       'episode-season', 'Multiple Entreprenuers'],
      dtype='object')
Index(['deal', 'description', 'episode', 'category', 'entrepreneurs',
       'location', 'company_website', 'askedFor', 'exchangeForStake',
       'valuation', 'season', 'shark1', 'shark2', 'shark3', 'shark4', 'shark5',
       'title', 'episode-season', 'Multiple Entreprenuers'],
      dtype='object')

**<center> Slicing DataFrames Using iloc and loc </center> **

In [ ]:
#How we can access specific rows within our dataframe? 
#iloc method => integer based location indexing

print(df.iloc[0,1]) #Prints out the 1st row and 2nd column. 

print(df.iloc[1:4,5:9]) #Prints out 2nd to 4th row and 6th to 9th row.

Bluetooth device implant for your ear.
       location                      company_website  askedFor  \
1  Somerset, NJ                  http://whybake.com/    460000
2   Atlanta, GA       http://www.avatheelephant.com/     50000
3     Tampa, FL  http://collegehunkshaulingjunk.com/    250000

   exchangeForStake
1                10
2                15
3                25

In [ ]:
#iloc isn't intuitive. At times, it better to use label-based filtering.
#The loc method allows us to do that 

#Suppose we want to print the 'valuation' and 'title' columsn of
#all the rows which belong to the Electronics category 

print(df.loc[df['category']=='Electronics',['valuation','title']])

#We can also filter results by boolean values. This outputs all rows in which
#the valuation is greater than 1000000.

print(df.loc[df['valuation']>1000000])

     valuation                title
39    15000000          VirtuSphere
45      200000           Mr. Poncho
46      750000             Ink Flip
94     1000000            Origaudio
110     100000          Tail Lightz
159    1515152  UniKey Technologies
212     207692          SoundBender
231     800000           Cellhelmet
303   20000000         Virtuix Omni
360    2333333                iLumi
379    1000000                Amber
403   30000000             Singtrix
457    2000000             luminAID
477   10000000     Melni Connectors
      deal                                        description  episode  \
0    False             Bluetooth device implant for your ear.        1
1     True  Retail and wholesale pie factory with two reta...        1
4    False  Interactive media centers for healthcare waiti...        1
5     True  One of the first entrepreneurs to pitch on Sha...        2
8    False  A safety device for seatbelts. It prevents the...        2
9     True  An educational record label and publishing hou...        2
12    True  A line of books written to help children find ...        3
13   False  Guitars with a folding neck, designed to fit i...        3
14   False  50 State Capitals in 50 Fun Minutes is the mos...        3
15   False  A franchise-model company offering professiona...        4
16    True  Coverplay is a slipcover for children's play y...        4
31   False  Concept for a live entertainment and amusement...        7
35   False  Fashion accessories company focused on its uni...        8
38    True  Women's apparel specially designed for sizes 1...        9
39   False            A virtual reality locomotion simulator.        9
41   False                  Probiotic food for dogs and cats.        9
44    True  An online service allowing high school athlete...       10
47   False   A chain of children's play and learning centers.       11
50    True  Designer helmets. The company owns a utility p...       11
57   False  A coffeehouse that is also a legal resource ce...       13
61   False  A liquid, organic fertilizer made from "llama ...       14
66   False  Premium wine sold by the glass in individually...        1
70    True  Allergy season bringing you down? Maybe it's t...        2
71   False  Vurtego is a high-tech pogo stick that is supe...        2
75   False  Pure Ayre Odor Eliminator is for anyone who ow...        3
81    True                   Light-up decals for car windows.        5
82   False  Small cases for mints, gum and contact lenses ...        5
89   False  A mobile entertainment company running special...        7
93   False  Non-stick fabric aisle runners for wedding cer...        8
95    True  Hy-Conn is a super-fast connector for fire hyd...        8
..     ...                                                ...      ...
441   True  GreenBox is the innovator behind the patented,...       16
442   True  If you're like most people, you can hardly fun...       16
444  False  BedJet is the world's first ultra-rapid coolin...       17
446   True  A stylish and eco-friendly alternative to pee ...       17
450  False  Innovative, healthy, and high-quality dog trea...       18
451  False  Sseko Designs is an ethical fashion brand that...       19
454  False  Lumi sells innovative printing kits that make ...       19
456  False  Keen Home makes smart devices to improve the c...       20
457   True  LuminAID is a solar-powered inflatable light d...       20
461   True  Coco Jack is a tool to safely and easily open ...       21
462  False  The BedRyder product is a removable seating sy...       21
463   True  EmazingLights is pioneering the new Gloving Mo...       22
464  False  Women's underwear characterized by attention t...       22
468  False  BrandYourself offers tools and services ensure...       23
469  False  The Home T is a stylish way to show your state...       23
472  False  Budsies magically transforms any artwork into ...       24
473  False  Bee Thinking crafts beautiful bee hives in Por...       24
474  False  Lightweight yet supportive and extremely comfo...       24
475  False  A technology platform allowing content creator...       25
477   True  Faster, safer, ergonomically correct and cost-...       25
478   True  An environmentally-friendly alternative to pea...       25
479   True  ZinePak partners with the world's top brands, ...       26
482  False  Buck Mason makes high-quality men's clothing i...       26
484  False  Frameri answers the question, "Why aren't your...       27
486   True  Zero Pollution Motors is launching the urban c...       27
488  False  Sunscreen Mist adds another point of access fo...       28
489   True  SynDaver Labs makes synthetic body parts for u...       28
491   True  Spikeball started out as a casual outdoors gam...       29
492   True  Shark Wheel is out to literally reinvent the w...       29
494   True  Sway Motorsports makes a three-wheeled, all-el...       29

                              category  \
0                            Novelties
1                       Specialty Food
4                    Consumer Services
5                       Specialty Food
8                           Automotive
9                            Education
12                 Baby and Child Care
13                               Music
14                           Education
15               Professional Services
16                 Baby and Child Care
31                       Entertainment
35                 Fashion Accessories
38                     Women's Apparel
39                         Electronics
41                        Pet Products
44                     Online Services
47   Baby and Children's Entertainment
50                  Outdoor Recreation
57               Professional Services
61                           Gardening
66                 Alcoholic Beverages
70               Health and Well-Being
71                      Toys and Games
75       Storage and Cleaning Products
81                          Automotive
82                           Novelties
89                       Entertainment
93                            Weddings
95                  Productivity Tools
..                                 ...
441      Storage and Cleaning Products
442      Storage and Cleaning Products
444                   Home Accessories
446                       Pet Products
450                       Pet Products
451              Men and Women's Shoes
454                          Novelties
456                   Home Accessories
457                        Electronics
461                      Kitchen Tools
462                         Automotive
463                     Party Supplies
464                    Women's Apparel
468                    Online Services
469            Men and Women's Apparel
472                     Toys and Games
473              Professional Services
474              Men and Women's Shoes
475                    Online Services
477                        Electronics
478                          Gardening
479                              Music
482            Men and Women's Apparel
484        Men and Women's Accessories
486                         Automotive
488                 Outdoor Recreation
489                          Education
491                     Toys and Games
492                 Outdoor Recreation
494                         Automotive

                                     entrepreneurs              location  \
0                                   Darrin Johnson          St. Paul, MN
1                                       Tod Wilson          Somerset, NJ
4                                   Kevin Flannery              Cary, NC
5                                      Susan Knapp       Napa Valley, CA
8                                    Robert Alison         Las Vegas, NV
9                                     Mark Furigay           Chicago, IL
12                                       Lori Lite          Marietta, GA
13                             Jeff and Josh Cohen         Livermore, CA
14                                    Ken Bradford            Dallas, TX
15                                      Paul Watts          Portland, OR
16                   Amy Feldman and Allison Costa       Los Angeles, CA
31                Todd Robbins and David Adamovich          New York, NY
35                                     Danon Beres  Huntington Beach, CA
38                                   Gayla Bentley           Houston, TX
39                    Ray Latypov and Jim Dimascio       Binghampton, NY
41   Dr. Geoffrey Broderick and Kristina Broderick        Huntington, NY
44                   Brian Duggan and Adam McCombs           Chicago, IL
47                        Michael and Babz Barnett        Blacksburg, VA
50               Marix Stone and Dr. Nancy Tanchel      Philadelphia, PA
57                           Jeff and Annie Hughes      Santa Monica, CA
61                             Aida and Phil Lough          La Habra, CA
66                                    James Martin        The Dalles, OR
70                                       Joe Moore   New Port Richey, FL
71                                   Brian Spencer     Mission Viejo, CA
75                                  James Mitchell              Kent, WA
81                   George Podd and Rolf Schwartz           Chicago, IL
82                                      Bob Kroupa           Chicago, IL
89                         Stuart and David Pikoff            Austin, TX
93                                   Julie Goldman         Montclair, NJ
95                                    Jeff Stroope           Ashdown, AR
..                                             ...                   ...
441         Ned Kensing and Jennifer Wright-Laracy          New York, NY
442                  Dan Barnes and Wesley LaPorte             Provo, UT
444                                    Mark Aramli           Newport, RI
446                                    Andrew Feld         Davenport, FL
450               Suman, Sujan and Nishes Shrestha          Mukilteo, WA
451                           Ben and Liz Bohannon          Portland, OR
454                                    Jesse Genet       Los Angeles, CA
456                   Nayeem Hussain and Ryan Fant          New York, NY
457                  Andrea Sreshta and Anna Stork            Oxford, MI
461                                   Dave Goodman            Austin, TX
462                                  George Conway           Austell, GA
463                                      Brian Lim       Los Angeles, CA
464                                Catalina Girald     San Francisco, CA
468                                 Patrick Ambron          New York, NY
469                                     Ryan Shell          New York, NY
472                                 Alex Furmansky        Lake Worth, FL
473                                      Matt Reed          Portland, OR
474                Joel Vinocur and Arsene Millogo      Indianapolis, IN
475             Alex Milewski and Sherisse Hawkins           Boulder, CO
477      Byron Dunn, Mark Melni, and Armand Eckert        Twin Falls, ID
478                                   Mont Handley        Pittsburgh, PA
479                   Kim Kaupe and Brittany Hodak          New York, NY
482              Sasha Koehn and Erik Schnakenberg       Los Angeles, CA
484                Konrad Billetz and Kevin Habich        Cincinnati, OH
486                     Ethan Tucker and Pat Boone         New Paltz, NY
488                     Tony Fayne and Josh Kaplan           Detroit, MI
489                       Dr. Christopher Sakezles             Tampa, FL
491                                    Chris Ruder           Chicago, IL
492               David Patrick and Zack Fleishman       Lake Forest, CA
494                                     Joe Wilcox         Palo Alto, CA

                                       company_website  askedFor  \
0                                                  NaN   1000000
1                                  http://whybake.com/    460000
4                              http://www.wispots.com/   1200000
5                          http://www.aperfectpear.com    500000
8                      http://www.nobucklenostart.com/    500000
9                                                  NaN    250000
12                       http://www.stressfreekids.com    250000
13                     http://www.voyageairguitar.com/    500000
14   http://www.amazon.com/50-State-Capitals-Fun-Mi...    155000
15                          http://removegraffiti.net/    350000
16                        http://www.coverplayard.com/    350000
31                                                 NaN    300000
35                                                 NaN    500000
38                        http://www.gaylabentley.com/    250000
39                         http://www.virtusphere.com/   1500000
41                  http://www.cornucopiapetfoods.com/    300000
44                         http://www.jumpforward.com/    150000
47                           http://www.rompnroll.com/    300000
50                   http://www.hellsbellscustoms.com/    500000
57                          http://www.legalgrind.com/    200000
61                           http://www.llamabrew.com/    125000
66                          http://www.copadivino.com/    300000
70                      http://www.filteryourlife.com/    500000
71                         http://www.vurtegopogo.com/    500000
75                            http://www.pureayre.com/    150000
81                              http://powerdecal.com/    100000
82                                 http://clipngo.com/    500000
89                                 http://www.g2u.com/    500000
93                     http://www.originalrunners.com/    250000
95                             http://www.hy-conn.com/    500000
..                                                 ...       ...
441                              http://greenboxny.com    300000
442                          https://www.phonesoap.com    300000
444                                  http://bedjet.com    250000
446                         https://www.freshpatch.com    150000
450                    http://www.himalayandogchew.com    750000
451                        http://www.ssekodesigns.com    300000
454                                    http://lumi.com    250000
456                             http://www.keenhome.io    750000
457                                http://luminaid.com    200000
461                           http://www.coco-jack.com    125000
462                            http://www.bedryder.com    200000
463                       http://www.emazinglights.com    650000
464                                 http://www.naja.co    500000
468                          https://brandyourself.com   2000000
469                            http://www.thehomet.com    250000
472                             http://www.budsies.com    100000
473                         http://www.beethinking.com    400000
474                           http://www.wearforus.com    200000
475                      https://www.beneaththeink.com    350000
477                     http://www.melniconnectors.com    500000
478                                http://pittmoss.com    600000
479                             http://www.zinepak.com    725000
482                          https://www.buckmason.com    200000
484                                https://frameri.com    150000
486                      http://zeropollutionmotors.us   5000000
488                       http://www.sunscreenmist.com    400000
489                                http://syndaver.com   3000000
491                               http://spikeball.com    500000
492                          http://www.sharkwheel.com    100000
494                     http://www.swaymotorsports.com    300000

     exchangeForStake  valuation  season            shark1            shark2  \
0                  15    6666667       1  Barbara Corcoran   Robert Herjavec
1                  10    4600000       1  Barbara Corcoran   Robert Herjavec
4                  10   12000000       1  Barbara Corcoran   Robert Herjavec
5                  15    3333333       1  Barbara Corcoran   Robert Herjavec
8                  10    5000000       1  Barbara Corcoran   Robert Herjavec
9                  10    2500000       1  Barbara Corcoran   Robert Herjavec
12                 20    1250000       1  Barbara Corcoran   Robert Herjavec
13                  5   10000000       1  Barbara Corcoran   Robert Herjavec
14                 10    1550000       1  Barbara Corcoran   Robert Herjavec
15                 15    2333333       1  Barbara Corcoran   Robert Herjavec
16                 15    2333333       1  Barbara Corcoran   Robert Herjavec
31                 20    1500000       1  Barbara Corcoran   Robert Herjavec
35                 25    2000000       1  Barbara Corcoran   Robert Herjavec
38                 20    1250000       1  Barbara Corcoran   Robert Herjavec
39                 10   15000000       1  Barbara Corcoran   Robert Herjavec
41                 15    2000000       1  Barbara Corcoran   Robert Herjavec
44                 10    1500000       1  Barbara Corcoran   Robert Herjavec
47                 10    3000000       1  Barbara Corcoran   Robert Herjavec
50                 20    2500000       1  Barbara Corcoran   Robert Herjavec
57                 15    1333333       1  Barbara Corcoran   Robert Herjavec
61                 10    1250000       1  Barbara Corcoran   Robert Herjavec
66                  5    6000000       2  Barbara Corcoran   Robert Herjavec
70                 10    5000000       2  Barbara Corcoran   Robert Herjavec
71                 20    2500000       2  Barbara Corcoran   Robert Herjavec
75                 10    1500000       2  Barbara Corcoran   Robert Herjavec
81                  5    2000000       2  Barbara Corcoran   Robert Herjavec
82                 30    1666667       2  Barbara Corcoran   Robert Herjavec
89                 10    5000000       2  Barbara Corcoran   Robert Herjavec
93                 15    1666667       2  Barbara Corcoran   Robert Herjavec
95                 40    1250000       2  Barbara Corcoran   Robert Herjavec
..                ...        ...     ...               ...               ...
441                10    3000000       6      Lori Greiner  Barbara Corcoran
442                 8    4000000       6      Lori Greiner  Barbara Corcoran
444                10    2500000       6      Lori Greiner  Barbara Corcoran
446                10    1500000       6      Lori Greiner  Barbara Corcoran
450                 5   15000000       6      Lori Greiner   Robert Herjavec
451                10    3000000       6      Lori Greiner  Barbara Corcoran
454                 5    5000000       6      Lori Greiner  Barbara Corcoran
456                10    7500000       6      Lori Greiner   Robert Herjavec
457                10    2000000       6      Lori Greiner   Robert Herjavec
461                10    1250000       6      Lori Greiner  Barbara Corcoran
462                15    1333333       6      Lori Greiner  Barbara Corcoran
463                 5   13000000       6      Lori Greiner   Robert Herjavec
464                 5   10000000       6      Lori Greiner   Robert Herjavec
468                14   14814815       6      Lori Greiner   Robert Herjavec
469                 5    5000000       6      Lori Greiner   Robert Herjavec
472                 5    2000000       6      Lori Greiner   Robert Herjavec
473                10    4000000       6      Lori Greiner   Robert Herjavec
474                15    1333333       6      Lori Greiner   Robert Herjavec
475                10    3500000       6      Lori Greiner  Barbara Corcoran
477                 5   10000000       6      Lori Greiner  Barbara Corcoran

**<center>Performing Mathematical Operations using Pandas </center> **

In [ ]:
#Sample Mathematical Operations 
#We are performing mathematical operations on the 'valuation' column for the examples.
print(df['valuation'].mean())
print(df['valuation'].median())
print(df['valuation'].std())
print(df['valuation'].max())
print(df['valuation'].min())
print(df['valuation'].count())

#Group By 

#When you apply the groupby function, you are 
#i) Splitting the data into groups based on the criteria you specify
#ii) Applying a function to each group
#iii) Finally, combined the results into one output


#The code below helps us find the median valuation across categories. 

print(df.groupby(['category']).median()['valuation'])

2165614.6767676766
1000000.0
3761971.0078376867
30000000
40000
495
category
Alcoholic Beverages                             6000000.0
Automotive                                      2000000.0
Baby and Child Care                              535714.5
Baby and Children's Apparel and Accessories      700000.0
Baby and Children's Bedding                      412500.0
Baby and Children's Entertainment                833333.0
Baby and Children's Food                        1500000.0
Consumer Services                               1000000.0
Costumes                                         708333.5
Cycling                                         1515152.0
Education                                       2250000.0
Electronics                                     1257576.0
Entertainment                                   1500000.0
Fashion Accessories                             2500000.0
Fitness Apparel and Accessories                  966666.5
Fitness Equipment                               1700000.0
Fitness Programs                                1000000.0
Furniture                                       1000000.0
Gardening                                       1250000.0
Golf Products                                    256250.0
Health and Well-Being                           1000000.0
Holiday Cheer                                    500000.0
Home Accessories                                1250000.0
Home Improvement                                 500000.0
Home Security Solutions                         2500000.0
Homeopathic Remedies                             533333.5
Kitchen Tools                                   1000000.0
Maternity                                       2075000.0
Men and Women's Accessories                     1116666.5
Men and Women's Apparel                         2500000.0
Men and Women's Shoes                           1333333.0
Men's Accessories                                400000.0
Mobile Apps                                    10900000.0
Music                                           6000000.0
Non-Alcoholic Beverages                          600000.0
Novelties                                        800000.0
Online Services                                 1000000.0
Outdoor Recreation                              1750000.0
Party Supplies                                  2000000.0
Personal Care and Cosmetics                      450000.0
Pest Control                                     325000.0
Pet Products                                     625000.0
Productivity Tools                               708333.0
Professional Services                           1000000.0
Specialty Food                                   833333.0
Storage and Cleaning Products                   1500000.0
Toys and Games                                  1000000.0
Undergarments and Basics                         300000.0
Water Bottles                                   1200000.0
Weddings                                        1195000.0
Wine Accessories                                 250000.0
Women's Accessories                              550000.0
Women's Apparel                                  500000.0
Women's Shoes                                    666666.5
Name: valuation, dtype: float64

If you have a question, you can post in the #programming-exercises channel on our Discord Server app: https://discord.gg/PqkB5b2.  You can also contact me at gpal@letslearn.tv. 
If you find these classes and notes beneficial, please consider leaving a tip at https://www.buymeacoffee.com/gpal. Thank you for your support!